### ISSUE TITLE
mvn test attempts to hit production endpoints. 

### ISSUE THREAD

**Issue by FodT** [MediaMath/t1-java#24]
`mvn test` should only run unit tests that do not require a network connection and instead work against mocked responses. Tests which require a network connection should ideally:
* be in a separate acceptance test suite
* hit sandbox where possible

**Comment by nitesh-chauhan** [comment]
in the pull request from Refactoring branch we have suppressed execution of functional tests and they wont hit any environment. since the functional test is for development purposes only we decided to not execute them. will run only when required, manually. this will be solved in other pull request once closed and merged to staging.

**Comment by fsargent** [comment]
This should be set in environment flags and not be committed into the code by branch.

**Comment by nitesh-chauhan** [comment]
this is done. and is available in the Refactoring pull request. 
mvn install -Pdev and mvn install -Pprod will run only unit tests. functional or integration tests will be ignored. if functional tests needs to be run then it needs to be done manually.
