### ISSUE TITLE
implicit login on ctor does not distinguish between invalid API key or invalid login credentials. 

### ISSUE THREAD

**Issue by FodT** [MediaMath/t1-java#25]
the `TerminalOne()` constructor calls `parseLoginError()` after making the login post. This will only return the single error on 403: 
"Authentication Failed: please provide valid credentials for the given environment"

regardless of whether the error was caused by a missing/invalid API key or invalid login credentials. 

Curiously, there's an (unused) `authenticate()` method which _does_ appear to properly handle the two cases.

**Comment by nitesh-chauhan** [comment]
oh. this is not an issue.. both the constructor and the authenticate method calls validateLoginCredentials(username, password, apiKey);  method to check if the user has supplied credentials before login...
also 
both the ctor and the authenticate method calls the same parseLoginError() after the login attempt ... which indicates the login has failed due to invalid api key or username / password. 
the parseLoginError is unable to differentiate what was invalid b'coz we get <h1>Developer Inactive</h1> as a response and its http status code is 403.
we dont have sufficient information on what went wrong hence we throw a "Authentication Failed: please provide valid credentials for the given environment" error msg.

**Comment by nitesh-chauhan** [comment]
@FodT can we mark this issue fixed? or can you verify the latest code and see if there is anything we can do to make it more user friendly?
